=== proxeeus/eventdecksimulator/trunk/data/xml/rules/whq-rules-schema.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     Warhammer Quest Monster Special Rules schema.
    </xsd:documentation>
  </xsd:annotation>

  <xsd:complexType name="ruleType">              
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="id"   type="xsd:string"/>
        <xsd:attribute name="name" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  
  <xsd:element name="rules">
    <xsd:complexType>
      <xsd:sequence maxOccurs="unbounded" minOccurs="1">
        <xsd:choice>
          <xsd:element name="rule" type="ruleType" />
          <xsd:element name="magic" type="ruleType" />
        </xsd:choice>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
</xsd:schema>

=== proxeeus/eventdecksimulator/trunk/debug/rpb-magic.xml
<?xml version="1.0"?>

<rules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	     xsi:noNamespaceSchemaLocation='whq-rules-schema.xsd'>

  <magic id="rpb-beastman" name="Beastman">A Beastman Shaman may cast spells at the start of each Monsters' Phase. Roll 2D6 on the following table to determine which.
2-5 Failure. The Shaman fails to cast a spell.
    6 Battle Lust. The Shaman gives an extra (1 x the Dungeon level)
    Attacks to the Monsters in combat with the Warriors, distributed as
    evenly as possible.
  7 Doombolt. A bolt of black fire bursts from the Shaman's palm
    towards one of the Warriors. Draw a Warrior counter to determine
    which Warrior is hit. The Doombolt inflicts (2 x the Dungeon
    level) Wounds, with no modifiers for Toughness or armour.
  8 Hand of Dust. The Shaman may attack any single adjacent
    Warrior. If there is more than one eligible target take a Warrior
    counter to determine which one the Shaman attacks. Roll 1D6 for
    the chosen Warrior and add his Strength to the score. Roll 2D6 for
    the Shaman and add his Strength to the score. The highest score
    wins. If the Warrior wins the spell fails.
    If the Shaman wins the Warrior suffers (2 x the Dungeon level)
    Wounds with no modifiers for Toughness or armour. If the
    Shaman is not in hand-to-hand combat ignore this result and re-roll
    on this table.
  9 Blade Wind. The Shaman summons a storm of slashing blades.
    Take a Warrior counter to determine who is affected. That Warrior
    suffers (the Dungeon level) D6 Wounds, modified for Toughness
    and armour as usual.
 10 Soul Drain. The Shaman creates a storm of dark magic. Roll 1D6
    for each Warrior adding his Toughness to the score. If the total is
    equal to or more than the Dungeon level he suffers no ill effects
    from the spell. If the score is less than the Dungeon level the
    Warrior suffers (1D6 + the Dungeon level) Wounds and the
    Shaman gains the same amount. The Shaman may never gain more
    Wounds than he started with - any extra Wounds are lost in the
    warp.
    A Warrior reduced to zero Wounds by this spell is immediately
    killed and may not he brought back to life by any means other than
    those spells and magic items that raise the dead.
 11 Arnizipal's Black Horror. A black cloud issues from the
    Shaman's mouth, engulfing the Warriors in darkness. Roll 1D6 for
    each Warrior adding his Strength to the score. If the total is 7 or
    more he suffers no ill effects from the spell. If the score is 6 or less
    he suffers (the Dungeon level) D6 Wounds, with no modifier for
    armour.
 12 Malediction of Nagash. The Shaman causes cuts to open up on
    the body of one of the Warriors. Draw a Warrior counter to
    determine which Warrior is hit. For 1 turn that Warrior is unable to
    move, fire a missile weapon, and is at -2 to all of his to hit rolls in
    close combat.
    Now, and at the start of each subsequent turn, the same Warrior
    loses (1 x the Dungeon level) Wounds. with no modifiers for
    Toughness or armour, until the Shaman is dead.</magic>
  <magic id="rpb-chaos" name="Chaos">At the start of each Monsters' Phase, a Chaos Sorcerer may cast one or more of the following spells. Roll the relevant number of D6 on the following table to determine which spells are cast:
2-4 Failure. The Sorcerer fails to cast this spell.
  5 Battle Lust. The Sorcerer gives an extra (1 x the Dungeon level) Attacks
    to the Monsters in combat with the Warriors, distributed as evenly as
    possible.
  6 Doombolt. A bolt of black fire bursts from the Sorcerer's palm towards
    one of the Warriors. Draw a Warrior counter to determine which Warrior
    is hit. The Doombolt inflicts (2 x the Dungeon level) Wounds, with no
    modifiers for Toughness or armour.
  7 Hand of Dust. The Sorcerer may attack any single adjacent Warrior. If
    there is more than one eligible target take a Warrior counter to
    determine who the Sorcerer attacks. Roll 1D6 for the chosen Warrior
    and add his Strength to the score. Roll 2D6 for the Sorcerer and add his
    Strength to the score. The highest score wins. If the Warrior wins the
    spell fails. If the Sorcerer wins the Warrior suffers (2 x the Dungeon
    level) Wounds with no modifiers for Toughness or armour.
    If the Chaos Sorcerer is not in hand-to-hand combat ignore this result
    and re-roll on this table.
  8 Blade Wind. The Sorcerer summons a storm of slashing blades. Take a
    Warrior counter to determine who is affected. That Warrior suffers (the
    Dungeon level) D6 Wounds, modified for Toughness and armour as
    usual.
  9 Soul Drain. The Sorcerer creates a storm of dark magic. Roll 1D6 for
    each Warrior adding his Toughness to the score. If the total is equal to
    or more than the Dungeon level he suffers no ill effects from the spell.
    If the score is less than the Dungeon Level the Warrior suffers (1D6 +
    the Dungeon level) Wounds and the Sorcerer gains the same amount.
    The Sorcerer may never gain more Wounds than he started with any
    extra Wounds are lost in the warp.
    A Warrior reduced to zero Wounds by this spell is immediately killed
    and may not be brought back to life by any means other than those
    spells and magic items that raise the dead.
 10 Amizipal's Black Horror. A black cloud issues from the Sorcerer's
    mouth, engulfing the Warriors in darkness. Roll i D6 for each Warrior
    adding his Strength to the score. If the total is 7 or more he suffers no
    ill effects from the spell. If the score is 6 or less he suffers (the
    Dungeon level) D6 Wounds, with no modifier for armour.
 11 Malediction of Nagash. The Sorcerer causes cuts to open up on the
    body of one of the Warriors. Draw a Warrior counter to determine
    which Warrior is hit. For 1 turn that Warrior is unable to move, fire a
    missile weapon, and is at -2 to all of his to hit rolls in close combat.
    Now, and at the start of each subsequent turn, the same Warrior loses
    (1 x the Dungeon level) Wounds, with no modifiers for Toughness or
    armour, until the Sorcerer is dead.
 12 The Transformation of Kadon. The Sorcerer transforms himself into
    one of the following monsters. Roll 1D6:
      1-2 Wyvern
      3-4 Chimera
       5  Manticore
       6  Hydra
    If the transformation turns the Sorcerer into a Monster of less value
    than himself, re-roll the spell.
    See the Monsters section of the Bestiary for full details and profiles for
    these Monsters.
    The Sorcerer remains transformed until either he or all of the Warriors
    are dead. While transformed he may not cast any more spells.</magic>
  <magic id="rpb-chaos-dwarf" name="Chaos Dwarf">At the start of each Monsters' Phase, a Chaos Dwarf Sorcerer may cast one or more of the following spells, depending on his Magic Rating. Roll the relevant number of D6 on the following table to determine which spells are cast:
  1 Doomroar. The Chaos Dwarf Sorcerer takes on the shape of the
    mighty Bull God Hashut and, with a shake of his horned head,
    gives a terrifying roar that goads his minions into action. This turn
    all Monsters get +1 Attacks.
  2 Eruption. The ground beneath one of the Warrior's feet erupts in a
    plume of magma. Draw a Warrior counter to determine which
    Warrior is affected. He suffers 5D6 Wounds, modified for
    Toughness and armour as usual
  3 Ash Cloud. The dungeon is suddenly filled with clouds of smoke
    and ash. All of the Warriors are at -2 on their to hit rolls for the
    next Warriors' Phase.
  4 Sorcerer's Curse. Cackling hideously the Chaos Dwarf Sorcerer
    utters a terrible curse on one of the Warriors. Draw a Warrior
    counter to determine who is affected. Unless he is given a healing
    potion or a healing spell is cast on him immediately the cursed
    Warrior is turned to stone and is out of the game. If he is given
    treatment, roll 1D6. On a score of 1. 2, 3 or 4 the Warrior is at -1
    Movement, -1 Initiative and -1 to hit until the Sorcerer is dead,
    when he returns to normal. On a score of 5 or 6 the spell has no
    effect at all.
  5 Lava Storm. With a majestic sweep of his arm the Sorcerer
    creates a stream of balls of molten lava. There are 2D6 balls and
    they are distributed amongst the Warriors evenly. Each causes 2D6
    Wounds, with no modifier for armour.
  6 Flames of Azgorh. The Sorcerer breathes out whirling tendrils of
    flame. Draw a Warrior counter to determine who is attacked. The
    target and every model adjacent to him, whether friend or foe,
    takes 2D6 Wounds, with no modifiers for Toughness or armour.
    Note that the Chaos Dwarf Sorcerer is the only model immune to
    the effects of the spell.</magic>
  <magic id="rpb-dark-elf" name="Dark Elf">At the start of each Monsters' Phase, a Dark Elf Sorcerer may cast one or more of the following spells. Roll 2D6 on the following table to determine which.
2-4 Failure. The Sorcerer fails to cast this spell.
  5 Battle Lust. The Sorcerer gives an extra (1 x the Dungeon level)
    Attacks to the Monsters in combat with the Warriors, distributed as
    evenly as possible.
  6 Doombolt. A bolt of black fire bursts from the Sorcerer's palm
    towards one of the Warriors. Draw a Warrior counter to determine
    which Warrior is hit. The Doombolt inflicts (2 x the Dungeon
    level) Wounds, with no modifiers for Toughness or armour.
  7 Hand of Dust. The Sorcerer may attack any single adjacent
    Warrior. If there is more than one eligible target take a Warrior
    counter to determine who the Sorcerer attacks. Roll 1D6 for the
    chosen Warrior and add his Strength to the score. Roll 2D6 for the
    Sorcerer and add his Strength to the score. The highest score wins.
    If the Warrior wins the spell fails. If the Sorcerer wins the Warrior
    suffers (2 x the Dungeon level) Wounds with no modifiers for
    Toughness or armour.
